version: "3"

services:
  notes-java-backend:
    container_name: notes-java-backend
    image: greenfrogab/notes-java:latest
    environment:
      - server.port=4000
      - spring.data.mongodb.port=27017
      - spring.data.mongodb.host=notes-java-mongodb
      - spring.data.mongodb.database=notes
    depends_on:
      - notes-java-mongodb
    links:
      - "notes-java-mongodb:notes-java-mongodb"
    ports:
      - "4000:4000"
    networks:
      - notes-java-network

  notes-java-mongodb:
    container_name: notes-java-mongodb
    image: mongo:latest
    networks:
      - notes-java-network

networks:
  notes-java-network:
    driver: bridge