name: Notes

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build and run test
        run: mvn clean install

      - uses: docker://docker:latest

      - name: List Docker images
        run: docker images

      - name: Checking docker version
        run: docker build -t greenfrogab/notes-java:latest .

      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_PASSWORD}}

      - name: Push image to docker hub
        run: docker push greenfrogab/notes-java:latest

      - name: Logout from Docker Hub
        run: docker logout

